spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudfactory?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181